# Generated by Django 4.1.6 on 2023-02-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_customers_employees_delete_customer_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('net', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='', upload_to='static/products/')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Shop.categories')),
            ],
        ),
    ]
